export const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_INVALID: 'AUTH_INVALID',
  AUTH_EXPIRED: 'AUTH_EXPIRED',
  AUTH_REVOKED: 'AUTH_REVOKED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  SCOPE_DENIED: 'SCOPE_DENIED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_CURSOR: 'INVALID_CURSOR',
  MEMORY_NOT_FOUND: 'MEMORY_NOT_FOUND',
  MEMORY_DUPLICATE: 'MEMORY_DUPLICATE',
  MEMORY_DELETED: 'MEMORY_DELETED',
  MEMORY_UNCHANGED: 'MEMORY_UNCHANGED',
  EMBEDDING_INVALID: 'EMBEDDING_INVALID',
  EMBEDDING_PROVIDER_NOT_CONFIGURED: 'EMBEDDING_PROVIDER_NOT_CONFIGURED',
  EMBEDDING_INPUT_EMPTY: 'EMBEDDING_INPUT_EMPTY',
  EMBEDDING_INPUT_TOO_LARGE: 'EMBEDDING_INPUT_TOO_LARGE',
  EMBEDDING_PROVIDER_ACCESS_DENIED: 'EMBEDDING_PROVIDER_ACCESS_DENIED',
  EMBEDDING_PROVIDER_THROTTLED: 'EMBEDDING_PROVIDER_THROTTLED',
  EMBEDDING_PROVIDER_TIMEOUT: 'EMBEDDING_PROVIDER_TIMEOUT',
  EMBEDDING_PROVIDER_RESPONSE_INVALID: 'EMBEDDING_PROVIDER_RESPONSE_INVALID',
  EMBEDDING_PROVIDER_UNAVAILABLE: 'EMBEDDING_PROVIDER_UNAVAILABLE',
  DRIVE_NOT_CONFIGURED: 'DRIVE_NOT_CONFIGURED',
  CONFLICT: 'CONFLICT',
  DATABASE_RETRY_EXHAUSTED: 'DATABASE_RETRY_EXHAUSTED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export class ServiceError extends Error {
  public readonly code: ErrorCode;
  public readonly statusCode: number;

  constructor(code: ErrorCode, message: string, statusCode: number = 400) {
    super(message);
    this.name = 'ServiceError';
    this.code = code;
    this.statusCode = statusCode;
  }
}
